version: '3.8' 
services: # apps containers you want to build and run
  anujapp1: # name da of appliction for compose 
    image: anujdotnetimg:v1  # image i want to build 
    build: .  # path of dockerfile location -- . means current 
    container_name: anujc1 # it will create container also 
  anujapp2: 
    image: anujhttpd:v1 
    build: 
      context: . #location of dockerfile 
      dockerfile: httpd.dockerfile # name of dockerfile 
    container_name: anujc2 
    ports:
      - 59999:80  
  
